### ISSUE TITLE
EventHub checkpoint offset mechanism probably will not work.

### ISSUE THREAD

**Issue by robblovell** [noodlefrenzy/node-sbus-amqp10#5]
Currently, using a filter x-opt-offset doesn't seem to work for checkpointing. There should be a way to tell the Event Hub to remember a checkpoint in the same way you can do this in the CSharp libraries.

**Comment by robblovell** [comment]
I am working with amqp10 v2.0.0 in another project that encapsulates the eventhub functionality. I have tried various options for checkpointing and have not been successful.

Here are a few notes:
[useful linformation](https://amqpnetlite.codeplex.com/wikipage?title=Using%20Amqp.Net%20Lite%20with%20Azure%20Server%20Bus%20Event%20Hub)

using this code to setup the filter:

``` coffeescript
Builder = require('node-amqp-encoder').Builder
offset = 60129550888
filter = {
                    'apache.org:selector-filter:string': @adapters.Translator(new Builder()
                    .described()
                    .symbol("apache.org:selector-filter:string")
                    .string("amqp.annotation.x-opt-offset > '" + offset + "'").encode())
                }
```

I have also tried a filter on the sequence number:

``` coffeescript
Builder = require('node-amqp-encoder').Builder
offset = 105495
 filter = {
                    'apache.org:selector-filter:string': @adapters.Translator(new @Builder()
                    .described()
                    .symbol("apache.org:selector-filter:string")
                    .string("amqp.annotation.x-opt-sequence-number > " + offset + "").encode())
                }
```

I have also tried different notations and variations for types: string, long, number etc... 
Also the accessor on amqp.annotation.x-opt-sequence-number could also need to be written amqp.annotation['x-opt-sequence-number'] as dashes isn't valid javascript, not sure.

**Comment by robblovell** [comment]
ServiceBusExplorer stores a checkpoint json file client side on exit that contains stuff like this:

``` json
[
  {
    "namespace": "stagetcuservicebusmojious",
    "eventHub": "vehicleeventhub",
    "consumerGroup": "testharnessconsumergroup",
    "leases": {
      "2": {
        "PartitionId": "2",
        "Owner": "ServiceBusExplorer",
        "Token": null,
        "Epoch": 0,
        "Offset": "68721645648",
        "SequenceNumber": 115761
      }
   }
}
```

**Comment by noodlefrenzy** [comment]
@robblovell I _believe_ this is now fixed - I've written an integration test against the date-based x-header to test it and ensure the behavior doesn't regress: https://github.com/noodlefrenzy/node-amqp10/blob/master/test/integration/servicebus/eventhubs/client.test.js#L53

Closing, but please let me know if you see issues.

**Comment by noodlefrenzy** [comment]
Hmm, seems like this actually _is_ an issue for node-amqp10, which was in fact broken when you opened this. However, that's now fixed, so re-closing.
